---

- hosts: all
  become: true
  tasks: 

  - name: install apache and php package
    package:
            name: 
                - "{{ httpd }}"
                - "{{ tmux }}"
                - "{{ php }}"         
            state: latest
            update_cache: yes
    
