---

- hosts: all
  become: true
  tasks: 

  - name: install updates
    yum:
            update_only: yes
            update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install apache and php package
    package:
            name: 
                - "{{ httpd }}"
                - "{{ tmux }}"
                - "{{ php }}"         
            state: latest
            update_cache: yes

- hosts: web_servers
  become: true
  tasks:

          - name: install apache and php for CentOS servers
            tags: centos, web servers, httpd, apache
            package:
                   name:
                           - httpd
                           - php
                   state: latest
            when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:
          - name: install mariadb package (CentOS)
            tags: database, mariadb, centos
            yum:
                    name:
                            - mariadb
                            - mariadb-server

                    state: latest
            when: ansible_distribution == "CentOS"


