---

- hosts: all
  become: true
  tasks: 

         - name: install updates
           yum:
                update_only: yes
                update_cache: yes
           when: ansible_distribution == "CentOS"

         - name: install apache and php package
           package:
                name: 
                    - "{{ httpd }}"
                    - "{{ tmux }}"
                    - "{{ php }}"         
                state: latest
                update_cache: yes

- hosts: all
  become: true
  tasks:
          - name: create simone user
            tags: always
            user:
                    name: simone
                    groups: root
          
           - name: add ssh key for simone
             tags: always
             authorized_key:
                     user: simone
                     key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCgOTqxbdKQGoDr38Z9WD2DU+BmWeouXhwCtxKcgfqEjBrCuVJj8QpITgnbLZ1yQ0uU5jWqPN4APj9DeUoiXab1TFDEuJ/bP2js1t/82CjshGrXTFFdqvW2OgzQr1fAY0D05GP23NlssrZe4mEFE4BzmF81ubHMMARzjY756HLzmmoYcBvGEwOAhz/kCrCnMUBadq5teGaSdYNm6BQppcRh/EPuCv1RUyVJyR0fEERU+rAn6AhOaQ8s8bqSSs2x11Q/eFKo79j9onG8UuR6zXVDkB1fFAep0TOA466kzsEWatWSsoA6xTTNbpdxBUmjUf5Zpvs4tKIw5M85iqn3SBKXUyfXaLbettepHDVYqxVXC5iRKEf4l2UgRrV9lX4h+etHnTrsmYMCHH3Dsij4sydnZjZebyA/FoSUxL/vF6ObPxppv/UfXy72rtFnvWNQuBha0DVCqGpWFFVuAaXMOZkqNF2GOGrStgzjHtGQ8MVNUKvWWm8z7UnuuHd+9md3Es8= root@localhost.localdomain
"         
    
- hosts: workstations
  become: true
  tasks:
          - name: install unzip
            package: 
                name: unzip

          - name: install terraform
            unarchive:
                src: https://releases.hashicorp.com/terraform/1.2.9/terraform_1.2.9_linux_arm64.zip
                dest: /usr/local/bin
                remote_src: yes
                mode: 0755
                owner: root
                group: root


- hosts: web_servers
  become: true
  tasks:

          - name: install apache and php for CentOS servers
            tags: centos, web servers, httpd, apache
            package:
                   name:
                       - httpd
                       - php
                   state: latest
            when: ansible_distribution == "CentOS"

          - name: copy default html file for site
            tags: html, webserver,httpd, apache2, apache
            copy: 
                   src: default_site.html
                   dest: /var/www/html/index.html
                   owner: root
                   group: root
                   mode: 0644

          - name: change e-mail address for admin
            tags: apache, centos, httpd
            lineinfile:
                    path: /etc/httpd/conf/httpd.conf
                    regexp: '^ServerAdmin'
                    line: ServerAdmin somebody@somewhere.net
            register: httpd

          - name: restart httpd (CentOS)
            tags: apache,centos,httpd
            service:
                    name: httpd
                    state: restarted
            when: httpd.changed

          - name: start httpd (CentOS)
            tags: httpd, apache2, apache
            ansible.builtin.systemd:
                    name: httpd
                    enabled: yes
                    state: started
            when: ansible_distribution == "CentOS"


- hosts: db_servers
  become: true
  tasks:
          - name: install mariadb package (CentOS)
            tags: database, mariadb, centos
            yum:
                    name:
                            - mariadb
                            - mariadb-server

                    state: latest
            when: ansible_distribution == "CentOS"


